name: michi-gato, library blorg praxis
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed
  
# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins_dir:
  - jekyll-feed
  - jekyll-sitemap

# Podcast Feed Settings
title:          Silver-Trees-Podcast
email:          test@podcast.org 
description:    "Preserve This Podcast is an Andrew W. Mellon grant-funded project hosted by the Metropolitan New York Library Council (METRO) to help podcasters protect their work against the threats of digital decay."
subtitle:       "A podcast about saving your podcast."
url:            http://michi-gato.github.io
lang:           Eng
author:         podPotato
copyright:      "CC BY 4.0"

feed:
  categories:
    - episodes

theme: jekyll-theme-minimal